### ISSUE TITLE
Window visualization error

### ISSUE THREAD

**Issue by javiavid** [Gru80/obsidian-regex-replace#11] opened 2022-05-12 14:20 UTC
Maybe it's because of the new obsidian version (my version is 0.14.10)
I have tried a new vault with the default theme.

![image](https://user-images.githubusercontent.com/7627504/168096581-c318b4bc-275d-495e-a462-83447214ecf9.png)

**Comment by Gru80** [comment] 2022-05-14 18:24
Thanks for the report,
unfortunately I don't have access to the insider builds, so I'm not yet able to reproduce it - but it definitely seems to be related to the new version since the GUI looks fine using the latest released version v0.14.6

It might be worth reporting that to the obsidian team as well, because there could be an issue with the dialog GUIs in general

**Comment by javiavid** [comment] 2022-05-15 08:39
We wait for you to have this version number in the public release so you can test it and see if it's a plugin issue or an obsidian issue.
Regarding notifying the obsidian team, I think it would be better for you to communicate, because I have no idea about programming and it will be easier for you.
Thank you very much

**Comment by Gru80** [comment] 2022-10-21 18:40
dialog looks fine for the latest released version (v1.0), so I'll close the issue for now

**Closed as completed by Gru80** 2022-10-21 18:40 UTC

**Comment by javiavid** [comment] 2022-10-23 10:13
Thanks
